# Generated by Django 4.2.7 on 2025-08-27 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('converted_text', models.TextField(help_text='Original transcribed text')),
                ('corrected_text', models.TextField(help_text='Grammar-corrected text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transcript',
                'verbose_name_plural': 'Transcripts',
                'ordering': ['-created_at'],
            },
        ),
    ]
